services:
  api:
    build: ./ # Diretório onde o Dockerfile do back-end está localizado
    container_name: backend-service
    env_file:
      - .env # Carrega as variáveis de ambiente do arquivo .env
    ports:
      - "${PORT}:${PORT}" # Usa a variável PORT do .env
    environment:
      - DATABASE_URL=${DATABASE_URL} # Passa o DATABASE_URL diretamente da variável de ambiente
    depends_on:
      - database
    networks:
      - my-network

  database:
    image: postgres:alpine # Imagem oficial do PostgreSQL no Docker
    container_name: database
    restart: always
    env_file:
      - .env # Carrega as variáveis de ambiente para o banco de dados também
    ports:
      - 5432:5432 # Usa a variável DB_PORT do .env
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistência dos dados do banco
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
